//app.js
App({
  onLaunch: function () {
    // 展示本地存储能力
    var logs = wx.getStorageSync('logs') || []
    logs.unshift(Date.now())
    wx.setStorageSync('img_list',[{
      id: 1,
      zan: '0',
      zan_tis: '取消',
      img: '../../img/1.jpg',
      width: 1300,
      height: 924

    }, {
      id: 2,
      zan: '0',
      zan_tis: '取消',
      img: '../../img/2.jpg',
      width: 1400,
      height: 1918
    }, {
      id: 3,
      zan: '0',
      zan_tis: '取消',
      img: '../../img/3.jpg',
      width: 1400,
      height: 2185
    }, {
      id: 4,
      zan: '0',
      zan_tis: '取消',
      img: '../../img/4.jpg',
      width: 1000,
      height: 1400
    }, {
      id: 5,
      zan: '80',
      zan_tis: '取消',
      img: '../../img/5.jpg',
      width: 1440,
      height: 1100
    }, {
      id: 6,
      zan: '12',
      zan_tis: '取消',
      img: '../../img/6.jpg',
      width: 1400,
      height: 1821
    }, {
      id: 7,
      zan: '3',
      zan_tis: '取消',
      img: '../../img/7.jpg',
      width: 1400,
      height: 1825
    }, {
      id: 8,
      zan: '9',
      zan_tis: '取消',
      img: '../../img/8.jpg',
      width: 1400,
      height: 1008
    }, {
      id: 9,
      zan: '56',
      zan_tis: '取消',
      img: '../../img/9.jpg',
      width: 1200,
      height: 1474
    }, {
      id: 10,
      zan: '6',
      zan_tis: '取消',
      img: '../../img/10.jpg',
      width: 1400,
      height: 1086
    }, {
      id: 11,
      zan: '3',
      zan_tis: '取消',
      img: '../../img/11.jpg',
      width: 900,
      height: 1359
    }, {
      id: 12,
      zan: '65',
      zan_tis: '取消',
      img: '../../img/12.jpg',
      width: 1200,
      height: 851
    }, {
      id: 13,
      zan: '1',
      zan_tis: '取消',
      img: '../../img/13.jpg',
      width: 1400,
      height: 1137
    }, {
      id: 14,
      zan: '0',
      zan_tis: '取消',
      img: '../../img/14.jpg',
      width: 1400,
      height: 1062
    }, {
      id: 15,
      zan: '45',
      zan_tis: '取消',
      img: '../../img/15.jpg',
      width: 1400,
      height: 1138
    }, {
      id: 16,
      zan: '70',
      zan_tis: '取消',
      img: '../../img/16.jpg',
      width: 1400,
      height: 898
    }, {
      id: 17,
      zan: '76',
      zan_tis: '取消',
      img: '../../img/17.jpg',
      width: 1400,
      height: 1048
    }, {
      id: 18,
      zan: '1',
      zan_tis: '取消',
      img: '../../img/18.jpg',
      width: 1400,
      height: 952
    }, {
      id: 19,
      zan: '4',
      zan_tis: '取消',
      img: '../../img/19.jpg',
      width: 1400,
      height: 1121
    }, {
      id: 20,
      zan: '1',
      zan_tis: '点赞',
      img: '../../img/20.jpg',
      width: 1400,
      height: 1113
    }, {
      id: 21,
      zan: '1',
      zan_tis: '点赞',
      img: '../../img/21.jpg',
      width: 1400,
      height: 1140
    }, {
      id: 22,
      zan: '1',
      zan_tis: '点赞',
      img: '../../img/22.jpg',
      width: 1400,
      height: 1261
    }, {
      id: 23,
      zan: '0',
      zan_tis: '取消',
      img: '../../img/23.jpg',
      width: 1400,
      height: 1724
    }, {
      id: 24,
      zan: '0',
      zan_tis: '取消',
      img: '../../img/24.jpg',
      width: 2000,
      height: 1645
    }, ],)

  },
  globalData: {
    userInfo: null
  }
})